### ISSUE TITLE
Dupe bug (cross-mod with carryon)

### ISSUE THREAD

**Issue by eudalia** [team-abnormals/environmental#155] opened 2021-03-12 23:41 UTC
With carryon, the items inside a slabfish with a chest (tested with BMO+blue backpack, and normal+pink sweater+pink backpack) will, at the same time, drop in the world and stay inside the slabfish in your hands, duping all the items easily.

**Comment by bageldotjpg** [comment] 2021-03-15 04:17
Duplicate of #133

**Closed by bageldotjpg** 2021-03-15 04:17 UTC
