### ISSUE TITLE
Quark recipes missing "mod_loaded" condition

### ISSUE THREAD

**Issue by WenXin20** [team-abnormals/environmental#150] opened 2021-03-08 22:56 UTC
`Minecraft v1.16.5`
`Forge v36.0.46`
`Environmental v1.0.0`

If Quark is not installed, the log prints out errors for missing recipes. A mod requirement can be added to the recipe json files.
```
"conditions": [
    {
      "type": "abnormals_core:quark_flag",
      "flag": "wooden_posts"
    },
    {
      "type":"forge:mod_loaded",
      "modid":"quark"
    }
  ]
```
[Log ](https://gist.github.com/WenXin20/9cd8168d2cda229a18f8bed968e7b5cf)

**Comment by bageldotjpg** [comment] 2021-03-09 03:00
Well.. there is an issue but thats not it. The recipe just has the wrong id.
The `abnormals_core:quark_flag` condition already handles the `mod_loaded` stuff.
The issue is that the recipe outputs as `quark:wisteria_post` but it should be `environmental:wisteria_post`

This issue is already fixed in dev though.

**Closed by bageldotjpg** 2021-03-09 03:00 UTC

**Comment by WenXin20** [comment] 2021-03-09 03:52
Ah, I didn't know that. Thanks.
